server {
listen 80;
listen [::]:80;
server_name localhost;

# Le dossier public contient l'index.html et les autres assets
root /var/www/html/public;

# Nginx sert l'index.html en premier pour la racine du site
index index.html index.php index.htm;

# Routeur pour l'API : toutes les requêtes qui commencent par /api/ seront gérées par le routeur PHP.
location /api/ {
    try_files $uri /index.php?$query_string;
}

# Si aucun fichier n'est trouvé, Nginx renvoie le fichier index.html.
location / {
    try_files $uri $uri/ /index.html;
}

# Les requêtes directes vers des fichiers .php sont bloquées pour des raisons de sécurité.
location ~ \.php$ {
    return 404;
}

# Passe les requêtes vers le bon serveur PHP-FPM
location ~ /api/.*\.php$ {
    fastcgi_pass php:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}

}