server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /var/www/html/public;
    index index.html index.php ;

    # Toutes les requêtes sont d'abord vérifiées pour voir si elles correspondent à un fichier ou un dossier existant.
    # Sinon, elles sont transmises à index.php pour être gérées par le routeur.
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Transmet les requêtes à PHP-FPM via FastCGI
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}