user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        server_name localhost;

        
        # On définit un alias pour le chemin d'URL "Ecoride/public/".
        # Les requêtes pour /Ecoride/public/... seront servies depuis /var/www/html/public/...
        location /Ecoride/public/ {
            alias /var/www/html/public/;
            index index.html;
            try_files $uri $uri/ /index.html =404;
        }

        # Une autre location pour gérer les autres requêtes, si nécessaire
        location / {
            root /var/www/html/;
            index index.html;
        }
    }
}