name: Sonarqube Scan

on:
  push:
    branches:
      - main
      - dev

jobs:
  analyze:
    name: Sonarqube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MiKa-lab-coder_Ecoride
            -Dsonar.organization=mika-lab-coder
            -Dsonar.sources=.
            -Dsonar.tests=tests/php/,tests/js/
            -Dsonar.exclusions=tests/php/**,tests/js/**